# Generated by Django 6.0 on 2026-03-01 05:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Thrissur', 'Thrissur'), ('Wayanad', 'Wayanad')], max_length=50)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('max_capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('full', 'Full'), ('closed', 'Closed')], default='active', max_length=20)),
                ('has_medical', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair / differently-abled accessible')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shelters',
            },
        ),
        migrations.CreateModel(
            name='ShelterManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, choices=[('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Thrissur', 'Thrissur'), ('Wayanad', 'Wayanad')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shelter_managers',
            },
        ),
        migrations.CreateModel(
            name='OverflowPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('probability', models.FloatField(help_text='0.0 to 1.0')),
                ('occupancy_at', models.IntegerField()),
                ('predicted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('features_used', models.JSONField(blank=True, null=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overflow_predictions', to='shelters.shelter')),
            ],
            options={
                'db_table': 'overflow_prediction_logs',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='ShelterAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overflow_high', 'Overflow Risk HIGH'), ('food_low', 'Food Running Low'), ('water_low', 'Water Running Low'), ('understaffed', 'Shelter Understaffed')], max_length=30)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='shelters.shelter')),
            ],
            options={
                'db_table': 'shelter_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='shelter',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelters', to='shelters.sheltermanager'),
        ),
        migrations.CreateModel(
            name='ShelterStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_occupancy', models.IntegerField()),
                ('food_status', models.CharField(choices=[('ok', 'OK'), ('low', 'Low'), ('critical', 'Critical'), ('out', 'Out')], default='ok', max_length=20)),
                ('water_status', models.CharField(choices=[('ok', 'OK'), ('low', 'Low'), ('critical', 'Critical'), ('out', 'Out')], default='ok', max_length=20)),
                ('medical_support', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_by', models.CharField(help_text='Volunteer name or manager username', max_length=200)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_synced', models.BooleanField(default=True, help_text='False if submitted offline and pending sync')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='shelters.shelter')),
            ],
            options={
                'db_table': 'shelter_status_updates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_type', models.CharField(choices=[('food', 'Food'), ('water', 'Water')], max_length=10)),
                ('quantity_available', models.FloatField(help_text='kg for food, litres for water')),
                ('consumption_rate', models.FloatField(default=0, help_text='per person per day estimate')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logged_by', models.CharField(max_length=200)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_logs', to='shelters.shelter')),
            ],
            options={
                'db_table': 'supply_logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.CharField(help_text='6-digit PIN for mobile login', max_length=6)),
                ('task', models.CharField(choices=[('cooking', 'Cooking'), ('registration', 'Registration'), ('cleaning', 'Cleaning'), ('medical', 'Medical Assistance'), ('logistics', 'Logistics'), ('security', 'Security'), ('general', 'General Help')], default='general', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resting', 'Resting'), ('off_duty', 'Off Duty')], default='active', max_length=20)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='shelters.shelter')),
            ],
            options={
                'db_table': 'volunteers',
            },
        ),
    ]
