# Generated by Django 5.2.8 on 2025-12-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="super_admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200, null=True)),
                ("password", models.CharField(max_length=200, null=True)),
                ("email", models.EmailField(max_length=120)),
                ("last_login", models.CharField(max_length=50, null=True)),
                ("is_active", models.IntegerField(null=True)),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "super_admin",
            },
        ),
    ]
