# Generated by Django 6.0 on 2025-12-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='public_users',
            table='public_users',
        ),
    ]
