# Generated by Django 6.0 on 2025-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_public_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_users',
            name='email_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
